### ISSUE TITLE
Naming and Usage

### ISSUE THREAD

**Issue by wellwelwel** [mysqljs/aws-ssl-profiles#5]
## Naming

In https://github.com/sidorares/node-mysql2/issues/2581#issuecomment-2046305122, the suggested name was `awsCaBundle`.

We should use this?

> Currently, the temporary name is just `profiles`.

---

## Usage

> Based in the current temporary name and prioritizing not _breaking changes_.

### mysqljs/mysql and node-mysql2

```js
const profiles = require('aws-ssl-profiles').profiles;

exports['Amazon RDS'] = profiles;
```

- <img width="413" alt="Screenshot 2024-04-10 at 08 10 12" src="https://github.com/mysqljs/aws-ssl-profiles/assets/46850407/06061627-f9cd-4dbd-b399-97044b7d710f">

---

### CJS (directly)

```js
const { profiles } = require('aws-ssl-profiles');
// ...

const conn = mysql.createConnection({
  ssl: profiles,
);
```

---

### ESM (directly)

```js
import { profiles } from 'aws-ssl-profiles';
// ...

const conn = mysql.createConnection({
  ssl: profiles,
);
```

---

### ℹ️ Notes

- The current profiles match the exact profiles from [**MySQL2 3.9.4**](https://github.com/sidorares/node-mysql2/blob/cf3fa60842e7e359db5b1d676f93a22ad6fea082/lib/constants/ssl_profiles.js).
  - Naturally, it doesn't fix any issues, such as https://github.com/sidorares/node-mysql2/issues/2581.
  - A simple alternative could be to organize the unique certificates from versions **< 3.9.4** and **>= 3.9.4**.
- I opted to use _named exports_ instead of _default exports_ to simplify use (and development) for both **CJS** and **ESM**. Please let me know if it's a problem.

**Comment by sidorares** [comment]
can we just have it as a default export, so we don't need to think about name?

```js
import profiles from 'aws-ssl-profiles';
```

also in mysql2 lib/constants/ssl_profiles.js we export an object with profiles where only key currently is `'Amazon RDS'`. I think the intention was to add later more profiles from other known services. Given that we haven't added any other, and repo name suggests it's aws focused, maybe we can just export here the content of `reauire('lib/constants/ssl_profiles.js')['Amazon RDS']`

Happy to discuss the scope here, and we at the stage when we can rename things easily:

- Are the any other AWS services that have different cert bundle?
- Are there any other popular services that might benefit from a npm packaged cert distribution?

**Comment by wellwelwel** [comment]
> can we just have it as a default export, so we don't need to think about name?

Of couse 🙋🏻‍♂️

**Comment by wellwelwel** [comment]
> maybe we can just export here the content of reauire('lib/constants/ssl_profiles.js')['Amazon RDS']

So, that's the current situation, but I just did a copy/paste, except for the TypeScript adaptation 🙋🏻‍♂️

https://github.com/mysqljs/aws-ssl-profiles/blob/2a986994cd4066ce083f6d41d21b48b22d10477a/src/profiles/ca/defaults.ts

---

Lastly, I created it in a way that we can add more certificates dinamically.

For example, the default option would be to bring in all the certificates, but we can also use an export for each certificate category individually.
